resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: smolit-hello-v2

namespace: smolit-hello

commonAnnotations:
  owner: smolit

namePrefix: smolit-hello-
nameSuffix: -v2